"""Initial migration

Revision ID: 136826214dc3
Revises: eee80d134c7c
Create Date: 2025-06-29 21:50:39.119839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136826214dc3'
down_revision = 'eee80d134c7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 